language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

services:
  - redis-server

before_script:
    - composer self-update
    - mysql -e "create database IF NOT EXISTS home;" -uroot

install:
   - composer update

script:
   - ./phake db:clear