language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly
# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7
    - php: hhvm
    - php: nightly

services:
  - redis-server

before_script:
    - composer self-update
    - mysql -e "create database IF NOT EXISTS home;" -uroot
    - echo 'extension=redis.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
   - composer update

script:
   - ./phake db:clear