<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 ' . $this->translate('skeleton_application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array(
        'rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'
    ))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/zf-table/zf-table.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->appendFile($this->basePath('js/jquery.min.js'))
        ->appendFile($this->basePath('js/jquery.dataTables.min.js'))
        ->appendFile($this->basePath('js/zf-table.js'))
    //        ->prependFile($this->basePath('js/bootstrap.min.js'))?>

</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home', [], true) ?>">
                &nbsp;<?php echo $this->translate('admin') ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('home', [], true) ?>"><?php echo $this->translate('home') ?></a></li>
                <?php if ($this->zfcUserIdentity()): ?>
                    <li>
                        <a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('sign_out'); ?>
                            ]</a></li>
                <?php endif ?>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>
<div class="container">
    <?php echo $this->content; ?>
    <footer>

    </footer>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
